### ISSUE TITLE
dark style for options html

### ISSUE THREAD

**Issue by kinghat** [Rayquaza01/changelogger#3]
you care if i tie in the dark theme to the options as well?

![image](https://user-images.githubusercontent.com/16073360/67220892-3184d400-f3f0-11e9-8711-7fcc64afa6cc.png)

**Comment by Rayquaza01** [comment]
I'd be fine with that.
Quick question: What version of Firefox are you using? Because on my end `about:addons` doesn't seem to change color with the theme (on both Release and Nightly).
![Screenshot from 2019-10-21 16-53-05](https://user-images.githubusercontent.com/22138871/67242393-7118e380-f423-11e9-89dd-b00deae5762c.png)

**Comment by kinghat** [comment]
> I'd be fine with that.
> Quick question: What version of Firefox are you using? Because on my end `about:addons` doesn't seem to change color with the theme (on both Release and Nightly).
> ![Screenshot from 2019-10-21 16-53-05](https://user-images.githubusercontent.com/22138871/67242393-7118e380-f423-11e9-89dd-b00deae5762c.png)

i apparently didnt get a notification that you commented. im running firefox dev edition:

![image](https://user-images.githubusercontent.com/16073360/67261468-629feb80-f466-11e9-886d-094c38e346a0.png)

i hadent themed the options page yet, i had just opened an issue to see if you wanted me to do it. new PR has it themed and functioning :ok_hand:

**Comment by kinghat** [comment]
merged here: https://github.com/Rayquaza01/changelogger/commit/eb1dcdc104fc693d8dcaabf2a5c29de8e84b433c

closing.
