### ISSUE TITLE
popup doesnt show if a changelog contains a link to AMO

### ISSUE THREAD

**Issue by kinghat** [Rayquaza01/changelogger#5]
ive done zero research on this but i just had an extension that was disabled get updated and now the popup doesnt show. havent tried restarting the browser yet. just documenting for now:

![image](https://user-images.githubusercontent.com/16073360/68793264-7f1ce700-0612-11ea-9e12-9d70c256344c.png)

**Comment by Rayquaza01** [comment]
This is a bug, but not because the extension was disabled when it updated.

When there are links in changelogs, the API gives the links so that links to external sites (sites that aren't AMO) go through a redirection server. (Here's an example from the Simple Tab Groups changelog: `https://outgoing.prod.mozaws.net/v1/92627baba4be31b5368a286a0e58b18eebd40aadcb009d1b26725e0b92f6ebeb/https%3A//bugzilla.mozilla.org/show_bug.cgi%3Fid=1595583`). Changelogger strips the redirect out.

In the changelog for Simple Tab Groups, there's also a link to another page on AMO (`https://addons.mozilla.org/firefox/addon/stg-plugin-create-new-tab/`). This doesn't have the redirect, so when Changelogger tries to remove the redirect, it breaks.
