### ISSUE TITLE
sync changelogger settings across devices

### ISSUE THREAD

**Issue by kinghat** [Rayquaza01/changelogger#6]
would like to sync the settings across devices if you would accept of pr when i get around to it?

**Comment by Rayquaza01** [comment]
Sure, I'll accept the PR if you make one

**Comment by kinghat** [comment]
i forgot to update the readme > options > theme documentation in the PRs

**Comment by Rayquaza01** [comment]
That's fine, I can add that myself. The `extension/docs/help.html` also needs to be updated.

**Comment by kinghat** [comment]
> The `extension/docs/help.html` also needs to be updated.

if you remove the theme section from this ill apply the styling/theme media queries to this as well, to bring it all together, later this afternoon or tomorrow.

**Comment by Rayquaza01** [comment]
I ended up removing the help page and moving most of the unique points it had into the README. It mainly said the same things as the README anyway.

I also did a decent bit of work cleaning up the code (adding comments, fixing the race condition bug, updating the AMO API version, converting to TypeScript, etc.) on the feature branch. I think it's pretty much ready to go, but I'd be happy to hear if you would like to make any changes/suggestions before I submit it.

**Comment by kinghat** [comment]
oh neat, ive been learning the basics of TS recently. i will give it a look over and see what you've done. i appreciate you valuing my opinion on the project :pray:

**Comment by kinghat** [comment]
looked over the feature branch rewrite, it looks really clean and i learned some things. first time seeing a semaphore. is that the fix for the race condition bug? i tested it a bit and didnt find any issues. theres no easy way to see the sync storage area or test the sync api though :man_shrugging: thanks for your work on refactoring the project!

superficially "updated" here could be "shown":
https://github.com/Rayquaza01/changelogger/blob/220187dec5e841b3b1b96baa19697bbeb23980c7/src/pages/options/options.html#L11 and the corresponding interface comment: https://github.com/Rayquaza01/changelogger/blob/220187dec5e841b3b1b96baa19697bbeb23980c7/src/OptionsInterface.ts#L2

**Comment by Rayquaza01** [comment]
Yes, the semaphore is the fix for the race condition bug. Saving the changelog to storage is actually 3 smaller steps, reading the current list, updating the list, and writing the new list. Because the WebExtension storage API is async, if 2+ extensions were installed/updated at basically the same time, the steps might execute out of order, causing some of the changelogs to not actually be saved. The semaphore "locks" storage so that it's guaranteed that only one changelog can be written at once, and that any others trying to access storage will have to wait for the lock to be released.

Good catch on that comment, it makes more sense as "shown".

And thanks again for your help on this version! I really appreciate it!

**Comment by Rayquaza01** [comment]
The new version should be up on AMO now. That was faster than expected! It only took 4 minutes for the submission to be approved.

**Comment by kinghat** [comment]
very nice. just came through for me and updated nicely. enjoy your week!
